Added FluffyMachines to addons page
Slimefun/Slimefun-Wiki pull request #62
Opened 2020-09-26 22:40 UTC by NCBPFluffyBear

Added FluffyMachines to addons page

2020-09-26 22:58 UTC, TheBusyBiscuit requested changes

2020-09-26 22:58 UTC, TheBusyBiscuit commented on pages/Addons.md
> +FluffyMachines | NCBPFluffyBear | <details><summary>expand</summary>This addon adds an assortment of miscellaneous machines, generators, and tools!</details> | [Readme](https://github.com/NCBPFluffyB
That description is a bit too generic, try to give an example or two for your content.

2020-09-27 05:16 UTC, LinoxGH approved these changes

2020-09-27 05:28 UTC, TheBusyBiscuit approved these changes

2020-09-27 05:30 UTC, merged